### ISSUE TITLE
The performances of pre-trained weights are lower than the paper

### ISSUE THREAD

**Issue by ydhongHIT** [WalBouss/SenFormer#6]
Hi, I notice that the performances of pre-trained weights you provided are lower than the paper. The results in the latest paper are obviously better. Do you have the plan to release the matched pre-trained weights?

**Comment by WalBouss** [comment]
Hi,
Thanks for reaching out!
Yes, I plan to release the weights for the latest version of the paper. I will try to do it by the end of the week.

**Comment by ydhongHIT** [comment]
> Hi, Thanks for reaching out! Yes, I plan to release the weights for the latest version of the paper. I will try to do it by the end of the week.

Thanks for your reply. May I ask what change makes the performance improvements?

**Comment by WalBouss** [comment]
It is the weight-sharing strategy that makes the performance improvements.

In **Table 2.** you can see that the _"repeated"_ setting allows keeping good performance while significantly reducing the number of parameters. Hence, _"repeated"_ weight-sharing can be seen as a form of regularization.
Moreover, this strategy seems to be even more beneficial for larger backbones (see **Tab.14** - Swin-L).

Hope that it answers your question.
